[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --prefix server"]

[phases.build]
cmds = ["npm run build --prefix server"]

[start]
cmd = "npm run start --prefix server"
